name: Systems
version: '1.0.0'
main: me.hektortm.woSSystems.WoSSystems
api-version: '1.21.8'
author: HektorTM
depend: [Core, WorldGuard, Citizens]
commands:
  debugcmd:
    description: Debug command
    usage: /<command> <player>
  # Interaction Commands
  interaction:
    description: interaction command
    usage: /<command> <reload|list|view|trigger>
    permission: interaction
    aliases: [ inter ]
  # Citem Commands
  citem:
    description: citem
    usage: /<command> <save|lore|name|flag> [arguments]
  cgive:
    description: give a citem
    permission: citem.give
    usage: /<command> <player> <ID> <amount>
  cremove:
    description: remove a citem
    permission: citem.remove
    usage: /<command> <player> <ID> <amount>
  sign:
    description: sign item
    permission: citem.sign
    usage: /<command>
  # CRecipe Commands
  crecipe:
    description: crecipe
    usage: /<command> <create> <id>
  # Stat Commands
  stats:
    description: Stats Command
    permission: stats.create
    usage: /<command> <create|delete|give|take|set|reset|view|reload|>
  globalstats:
    description: global stats command
    permission: stats_global.create
    usage: /<command>
  # Unlockable Commands
  unlockable:
    description: Unlockable Command
    permission: unlockable.create
    usage: /<command> <give|take>
  # Economy Commands
  economy:
    aliases: [ eco ]
    usage: /<command>
    description: Economy
    permission: economy.modify.give
  balance:
    aliases: [ bal ]
    description: Shows your or a players balance
    usage: /<command> [player]
    permission: economy.balance.self
  pay:
    description: pay some1 money
    usage: /pay <player>
    permission: economy.pay
  coinflip:
    description: GAMBLING
    usage: /coinflip <amount> <heads|tails>
    permission: economy.coinflip
  # Chat System Commands
  channel:
    aliases: [ch]
    description: chat
    usage: /ch <join|focus|leave>
    permission: chat.channel.join
  nickname:
    aliases: [nick]
    description: nick
    permission: nick.request.send
    usage: /<command>
  realname:
    description: realname
    usage: /<command> <input>
  # Loottable Commands
  loottable:
    aliases: [lt]
    description: loottable
    permission: loottable.give
    usage: /<command> give
  # Time Commands
  time:
    description: View and manipulate the time
    usage: /<command> [date|reload|freeze]
  internalviewitem:
    description: Internal command for viewing items.
    usage: /internalviewitem <clickId>
# Cosmetic Commands
  cosmetic:
    description: cosmetic management
    usage: /<command>
  prefixes:
    description: open Prefix Menu
    uasge: /<command>
    aliases: [prefix]
  badges:
    description: open Badge Menu
    uasge: /<command>
    aliases: [badge]
  titles:
    description: open Title Menu
    uasge: /<command>
  # Profile Command
  profile:
    description: profile
    usage: /<command> <player>

  gui:
    description: open GUIs for players
    usage: /<command> <open> <player> <id>

  cooldown:
    description: cooldown management
    usage: /<command> <give|remove|view> <player> <id>
    aliases: [cd]

  calendar:
    aliases: [calender, cal]
    description: calendar management
    usage: /<command> <view|set> [date]

  link:
    description: link management
    usage: /<command> <website|discord> [code]
    permission:

  dialog:
    description: Dialog Command
    usage: /<command> <start|stop|reload> [player|id]
